- id: pipfile-sort
  name: Sorts pipfile.
  description: Sort package dependency lists in Pipfile, namely 'packages' and 'dev-packages'
  entry: pipfile-sort
  language: python
  pass_filenames: false
